api-token: RGAPI-6e7894f3-8ea6-416c-99de-1aa6f8c63dd7

mongodb:
  uri: mongodb://localhost:27017
  dbname: tft_service


feign:
  tft:
    krApi:
      name: krApiClient
      url: https://kr.api.riotgames.com
    asiaApi:
      name: asiaApiClient
      url: https://asia.api.riotgames.com


#spring:
#  data:
#    mongodb:
#      host: 10.201.213.51
#
#      port: 25017
#      database: ads_service