break-time: 2000

feign:
  tft:
    krApi:
      name: krApiClient
      url: https://kr.api.riotgames.com
    asiaApi:
      name: asiaApiClient
      url: https://asia.api.riotgames.com

#h2 console 활성화 및 경로 설정

#h2 db 설정

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
spring:
  main:
    web-application-type: none
