spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tft_service
  config:
    import: classpath:jasypt-password.yml
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${jasyptPassword}

aws:
  dynamodb:
    endpoint: http://localhost:8000

api-token: RGAPI-7ed72333-bf3b-4de7-bdae-7f6014243a19
