spring:
  data:
    mongodb:
      host: ENC(devfvfVTBgttT1Yb5FXLQSAoy2AcVn93vCimn6lljLi2C5OesG7hsp468iF4nOhSyIO+LvbKrDy0Wc6NE1Gn/w==)
      port: 27017
      database: ENC(qF9jt3azp8GUIk1m9fkOZ45FkVKm6hpZ)
      username: ENC(U9b7OmLUZ9Z5GPHkGOkFoA==)
      password: ENC(1PI6z4vKKl4w36lYhZfxhZwWeWHYOHUukDDkw8s/OUw=)
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${jasyptPassword}

api-token: ENC(TkzX6bFai6xA6yU9lFx5L7aOa9JtuT3Aw5peYxXTeTvpvoOmT7X2B9SbJdugY0sygeVP8c65TiA=)
slack.token: ENC(IVD2Sq2qSXByzUcZQMv6b6fQxnoSrn+dsKSdf9W4XwZdO3kjMX7AsRYz0kRJTrUZ4OdyOtIy1wUPCey04lzFYA==)