api-token: RGAPI-346ae5ae-0af5-48a2-84e5-4894b3874047
break-time: 1500

mongodb:
  uri: mongodb://localhost:27017
  dbname: tft_service


feign:
  tft:
    krApi:
      name: krApiClient
      url: https://kr.api.riotgames.com
    asiaApi:
      name: asiaApiClient
      url: https://asia.api.riotgames.com

#h2 console 활성화 및 경로 설정

#h2 db 설정
spring:
  datasource:
    url: jdbc:h2:mem:testDB
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true   # 아름답게 출력
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  h2:
    console:
      enabled: true
      path: /h2-console

#spring:
#  data:
#    mongodb:
#      host: 10.201.213.51
#
#      port: 25017
#      database: ads_service