on:
  push:
    branches:
      - main
      -
jobs:
  deploy-elastic-beanstalk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build --tag owl2274/tft-api-batch:latest .
          docker push owl2274/tft-api-batch:latest